

var quotes = ["SIGN UP FOR PORNHUB PREMIUM, BECAUSE LIFE IS SHORT.",
"STOP LIVING A LIE. I’M NOT HEALTHGOTH, I’M JUST GOTH.", "WIN, EVEN THOUGH THEY DON’T WANT ME TO.",
"OWN THE AWKWARD SERIES OF SOUNDS AND GESTURES THAT PASS FOR ME TRYING TO SOCIALIZE AT PARTIES.",
"STOP APOLOGIZING FOR THE THOUSANDS OF LOST DOLLARS AND IRREDEEMABLE SADNESS I’VE INFLICTED ON MY LOVED ONES BECAUSE OF THE KIM KARDASHIAN APP.",
"BUY AND READ MORE BOOKS, AND ONLY SOMETIMES MENTION THAT FACT IN THE HOPES OF GETTING SOMEONE TO TOLERATE ME TOUCHING THEM.",
"MAKE IT THE YEAR OF YES. YES TO MY DREAMS. YES TO MY FRIENDS. YES TO KETAMINE.",
 "DEDICATE MYSELF TO REALLY TAKING THE NEXT STEP ON MY VAMPIRE DIARIES RECAP VLOG.",
  "STOP QUOTING DJ KHALED IRONICALLY AND FOCUS ON THE SINCERITY OF HIS MESSAGE.", "SNAPCHAT FOR SOMETHING I BELIEVE IN AND NOT JUST MYSELF.", "TAKE A STAND AGAINST PEOPLE WHO STEAL MEMES. I NEED TO DO IT FOR THE CHILDREN.", "QUIT ALL SOCIAL MEDIA TO TAKE MORE TIME TO REALLY FOCUS ON ME, MY HEART SONG, AND ZONING OUT THE HATERS THAT ARE KEEPING ME FROM ESPORTS GREATNESS.", "MAKE ARTISANAL WOOL HEADWEAR ACCESSIBLE TO EVERYONE, NOT JUST THE PRIVILEGED ELITE.", "START FROM THE BOTTOM AND EVENTUALLY END UP HERE.",
  "PROVE THE DOUBTERS WRONG AND TAKE MY POUR-OVER COFFEE GAME TO THE NEXT LEVEL.", "GET #G-I-R-L-B-O-S-S TATTOOED ACROSS MY KNUCKLES.", "STOP DRINKING AND PICKING FISTFIGHTS AT MY COWORKING SPACE.",
  "STOP LETTING KINFOLK TELL ME HOW LIVE MY LIFE AND START LETTING KANYE TELL ME HOW TO LIVE MY LIFE.", "MOVE ‘LAY IN THE FETAL POSITION, NUMBLY CONSIDERING THE HORROR AND MEANINGLESS OF MY JOB AND RELATIONSHIPS’ TO THE BOTTOM OF MY TO DO LIST INSTEAD OF THE TOP.",
  "TAKE THAT METAL WORKING CLASS TO REALLY GET IN TOUCH WITH MY MAKER ROOTS, JUST LIKE MY GRANDFATHER DID WHEN HE WORKED HIS ENTIRE LIFE TO MAKE SURE THAT I’D NEVER HAVE TO BE A METAL WORKER.", "GO VIRAL ON YOUTUBE FOR THE RIGHT REASONS.", "STOP CARRYING INFINITE JEST AROUND WITH ME FOR ATTENTION AND START USING INFINITE JEST TO RETURN BALANCE TO MY CLEARLY BROKEN COUCH.", "STOP ACCIDENTALLY SITTING ON CONTEMPORARY ARTWORK.", "TRAVEL TO INDIA. I HAVE A FEELING INDIA WILL FOREVER BE A PART OF ME.", "REALLY WORK ON MY MOST PHOTOGENIC YOGA POSES.", 
  "WORK ON REALLY SCALING MY ETSY SHOP.", "STOP STRESSING AND JUST GET MARRIED. THEN STOP STRESSING AND JUST GET DIVORCED.", "STOP NEGATIVELY COMPARING MY LIFE TO BEYONCE’S AND START POSITIVELY COMPARING MY LIFE TO THE OTHER MEMBERS OF DESTINY’S CHILD.",
  "JOIN ISIS FOR A LITTLE BIT, THEN REALISE THAT IT ISN’T FOR ME.", "KEEP THE SPIRIT OF BURNING MAN IN MY HEART ALL YEAR ROUND.", "STOP PASSING OUT DRUNK ON MY YOGA MAT.", "INSPIRE ALL OF MY FRIENDS TO TAKE IT TO THE NEXT LEVEL THROUGH MY NIKE+ POSTS, ONE ‘GRAM AT A TIME!", "STOP APOLOGIZING FOR NOT HAVING CHILDREN AND START CELEBRATING MY EXPERTLY CURATED PINTEREST.", "FEEL THE SAME PASSION ABOUT MY VARIOUS MEANINGLESS LIFE CHOICES AS I DO ABOUT DRAKE.", "STOP BEING A BURDEN ON MY PARENTS AND START BEING A BURDEN ON MY SIGNIFICANT OTHER.", "STOP SEEKING VALIDATION ON INSTAGRAM AND START SEEKING VALIDATION FROM MY PETS.", "DEDICATE MY CROSSFIT WOD TO ALL THE AWESOME KICKSTARTERS THAT JUST DIDN’T MAKE IT.", "APPROACH DONDA FOR AN UNPAID INTERNSHIP BEFORE GOING TO GRAD SCHOOL.", "MOVE TO BALI AND BE THE SCULPTOR I’M FULLY AWARE I’M NOT TALENTED ENOUGH TO BE.",
  "GET MY INSTAGRAM ACCOUNT VERIFIED. LIKE, FINALLY."


              ];
var quoteButton = document.getElementById('quoteButton');
var quoteDiv = document.getElementById('quoteDiv');


function randomNumber() {
 return Math.floor((Math.random() * quotes.length) );
};

function divQuote() {
  var quotePosition = randomNumber();
  quoteDiv.innerHTML = quotes[quotePosition];
}

quoteButton.addEventListener("click", divQuote);
